mainSections:
  - posts
description: I am Xunzhuo(刘训灼) from China. I am working at Tencent Cloud Mesh team in Tencent Cloud. I am focusing on Istio, Kubernetes, EnvoyProxy, WebAssembly.

repoEditURL: https://github.com/Xunzhuo/Blog/tree/master/exampleSite/

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme: dark

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/log.png
publisherName: 刘训灼
publisherLogo: images/log.png

highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/master/build/languages for available languages.
    languages:
      - dart
    # See https://github.com/highlightjs/cdn-release/tree/master/build/styles for available styles.
    style: solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

comment:
  # Options: disqus, commento, valine and utterances.
  handler: utterances

  disqus:
    shortname: xunzhuo.disqus.com

  utterances:
    # Browse https://utteranc.es/ to see the options available.
    # If you want the color scheme of utterances to follow eureka's, you can set `theme: eureka`.
    repo: Xunzhuo/Blog
    issue-term: title
    label: "Comment"
    theme: github-dark

  # commento:
  #   # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
  #   url:

  valine:
    # Browse https://valine.js.org/en/configuration.html to see the options available.
    # You can list the key and value you want as below.
    # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
    # For example, `appId` should be written as `app-Id` or other acceptable formats.
    app-Id: xUnOmpBlCPQD0GKnqk7lIroc-gzGzoHsz
    app-Key: RrbhtwkTF6iYy0xz3kL0wREq

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme: 
  #   flowchart:
  #     diagram-padding:
